[package]
name = "theme_clipper"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
walkdir = "2"
indicatif = "0.17"
rand = "0.8"
serde = {version="1.0.219", features = [ "derive"]}
serde_json = "1.0.143"

